### ISSUE TITLE
etherport + firmata throws es6-shim bad set error

### ISSUE THREAD

**Issue by soundanalogous** [rwaldron/etherport#8]
If I create a new empty project, npm install `firmata` (eventually swapping with my firmata serial branch once I get this to work) and `etherport` and try to run blink-firmata like this:

```JavaScript
var Firmata = require("firmata").Board;
var EtherPort = require("etherport");
var board = new Firmata(new EtherPort(3030));

board.on("ready", function() {
  console.log("READY!");
  console.log(
    board.firmware.name + "-" +
    board.firmware.version.major + "." +
    board.firmware.version.minor
  );

  var state = 1;

  this.pinMode(8, this.MODES.OUTPUT);

  setInterval(function() {
    this.digitalWrite(8, (state ^= 1));
  }.bind(this), 500);
});
```
I get the following error:
```JavaScript
/Users/soundanalogous/Desktop/etherport-test/node_modules/etherport/node_modules/es6-shim/es6-shim.js:2079
            throw new TypeError('bad set');
                  ^
TypeError: bad set
    at new Set (/Users/soundanalogous/Desktop/etherport-test/node_modules/etherport/node_modules/es6-shim/es6-shim.js:2079:19)
    at /Users/soundanalogous/Desktop/etherport-test/node_modules/etherport/node_modules/es6-shim/es6-shim.js:2218:9
    at isCallableWithoutNew (/Users/soundanalogous/Desktop/etherport-test/node_modules/etherport/node_modules/es6-shim/es6-shim.js:22:22)
    at Object.<anonymous> (/Users/soundanalogous/Desktop/etherport-test/node_modules/etherport/node_modules/es6-shim/es6-shim.js:27:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Any idea how to resolve this? I'm trying to test Firmata serial integration in StandardFirmataEthernet and this is the first step.

**Comment by soundanalogous** [comment]
Resolved this. It seems the es6-shim lib has a conflict in node 0.10 and older versions of node 0.12. Turns out I had to install the latest version of node first, then reinstall etherport and firmata. Then swap the installed firmata.js with the serial version. Ethernet with Firmata serial is working now.
